# Enable nuSIM Application LIB
CONFIG_LIB_NUSIM=y
CONFIG_LIB_NUSIM_AT=y
CONFIG_AT_CMD_PARSER=y

# Enable RT nuSIM TFM partition service
CONFIG_TFM_PARTITION_RT_NUSIM=y

# PM size without MCUBoot
CONFIG_PM_PARTITION_SIZE_TFM=0x30000
