# Enable nuSIM Application LIB
CONFIG_LIB_NUSIM=y
CONFIG_LIB_NUSIM_AUTO_SELECT=n

# PM size without MCUBoot
CONFIG_PM_PARTITION_SIZE_TFM=0x30000

CONFIG_NRF_MODEM_LIB_SHMEM_TRACE_SIZE_OVERRIDE=y
CONFIG_NRF_MODEM_LIB_SHMEM_TRACE_SIZE=32768
